config/routes.rb
Rails.application.routes.draw do
  resources :direccions
  resources :usuarios
  get 'index/inicio'

end

app/models/direccion.rb
class Direccion < ActiveRecord::Base
  belongs_to :usuario
end

app/models/usuario.rb
class Usuario < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/direccions_controller.rb
class DireccionsController < ApplicationController
  before_action :set_direccion, only: [:show, :edit, :update, :destroy]

  # GET /direccions
  # GET /direccions.json
  def index
    @direccions = Direccion.all
  end

  # GET /direccions/1
  # GET /direccions/1.json
  def show
  end

  # GET /direccions/new
  def new
    @direccion = Direccion.new
  end

  # GET /direccions/1/edit
  def edit
  end

  # POST /direccions
  # POST /direccions.json
  def create
    @direccion = Direccion.new(direccion_params)

    respond_to do |format|
      if @direccion.save
        format.html { redirect_to @direccion, notice: 'Direccion was successfully created.' }
        format.json { render :show, status: :created, location: @direccion }
      else
        format.html { render :new }
        format.json { render json: @direccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /direccions/1
  # PATCH/PUT /direccions/1.json
  def update
    respond_to do |format|
      if @direccion.update(direccion_params)
        format.html { redirect_to @direccion, notice: 'Direccion was successfully updated.' }
        format.json { render :show, status: :ok, location: @direccion }
      else
        format.html { render :edit }
        format.json { render json: @direccion.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /direccions/1
  # DELETE /direccions/1.json
  def destroy
    @direccion.destroy
    respond_to do |format|
      format.html { redirect_to direccions_url, notice: 'Direccion was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_direccion
      @direccion = Direccion.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def direccion_params
      params.require(:direccion).permit(:calle, :numero, :comuna, :cuidad, :pais, :usuario_id)
    end
end

app/controllers/index_controller.rb
class IndexController < ApplicationController
  def inicio
  end
end

app/controllers/usuarios_controller.rb
class UsuariosController < ApplicationController
  before_action :set_usuario, only: [:show, :edit, :update, :destroy]

  # GET /usuarios
  # GET /usuarios.json
  def index
    @usuarios = Usuario.all
  end

  # GET /usuarios/1
  # GET /usuarios/1.json
  def show
  end

  # GET /usuarios/new
  def new
    @usuario = Usuario.new
  end

  # GET /usuarios/1/edit
  def edit
  end

  # POST /usuarios
  # POST /usuarios.json
  def create
    @usuario = Usuario.new(usuario_params)

    respond_to do |format|
      if @usuario.save
        format.html { redirect_to @usuario, notice: 'Usuario was successfully created.' }
        format.json { render :show, status: :created, location: @usuario }
      else
        format.html { render :new }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /usuarios/1
  # PATCH/PUT /usuarios/1.json
  def update
    respond_to do |format|
      if @usuario.update(usuario_params)
        format.html { redirect_to @usuario, notice: 'Usuario was successfully updated.' }
        format.json { render :show, status: :ok, location: @usuario }
      else
        format.html { render :edit }
        format.json { render json: @usuario.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /usuarios/1
  # DELETE /usuarios/1.json
  def destroy
    @usuario.destroy
    respond_to do |format|
      format.html { redirect_to usuarios_url, notice: 'Usuario was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_usuario
      @usuario = Usuario.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def usuario_params
      params.require(:usuario).permit(:nombre, :apellido, :fechanacimiento, :correo)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/direccions_helper.rb
module DireccionsHelper
end

app/helpers/index_helper.rb
module IndexHelper
end

app/helpers/usuarios_helper.rb
module UsuariosHelper
end

app/views/direccions/_form.html.erb
<%= form_for(@direccion) do |f| %>
  <% if @direccion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@direccion.errors.count, "error") %> prohibited this direccion from being saved:</h2>

      <ul>
      <% @direccion.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :calle %><br>
    <%= f.text_field :calle %>
  </div>
  <div class="field">
    <%= f.label :numero %><br>
    <%= f.number_field :numero %>
  </div>
  <div class="field">
    <%= f.label :comuna %><br>
    <%= f.text_field :comuna %>
  </div>
  <div class="field">
    <%= f.label :cuidad %><br>
    <%= f.text_field :cuidad %>
  </div>
  <div class="field">
    <%= f.label :pais %><br>
    <%= f.text_field :pais %>
  </div>
  <div class="field">
    <%= f.label :usuario_id %><br>
    <%= f.select( "usuario_id",Usuario.all.collect{|1| [ 1.nombre, 1.id ] }, {include_blank: 'Seleccione Usuario'}) %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/direccions/edit.html.erb
<h1>Editing Direccion</h1>

<%= render 'form' %>

<%= link_to 'Show', @direccion %> |
<%= link_to 'Back', direccions_path %>

app/views/direccions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Direccions</h1>

<table>
  <thead>
    <tr>
      <th>Calle</th>
      <th>Numero</th>
      <th>Comuna</th>
      <th>Cuidad</th>
      <th>Pais</th>
      <th>Usuario</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @direccions.each do |direccion| %>
      <tr>
        <td><%= direccion.calle %></td>
        <td><%= direccion.numero %></td>
        <td><%= direccion.comuna %></td>
        <td><%= direccion.cuidad %></td>
        <td><%= direccion.pais %></td>
        <td><%= direccion.usuario %></td>
        <td><%= link_to 'Show', direccion %></td>
        <td><%= link_to 'Edit', edit_direccion_path(direccion) %></td>
        <td><%= link_to 'Destroy', direccion, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Direccion', new_direccion_path %>

app/views/direccions/new.html.erb
<h1>New Direccion</h1>

<%= render 'form' %>

<%= link_to 'Back', direccions_path %>

app/views/direccions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Calle:</strong>
  <%= @direccion.calle %>
</p>

<p>
  <strong>Numero:</strong>
  <%= @direccion.numero %>
</p>

<p>
  <strong>Comuna:</strong>
  <%= @direccion.comuna %>
</p>

<p>
  <strong>Cuidad:</strong>
  <%= @direccion.cuidad %>
</p>

<p>
  <strong>Pais:</strong>
  <%= @direccion.pais %>
</p>

<p>
  <strong>Usuario:</strong>
  <%= @direccion.usuario.nombre %>
</p>

<%= link_to 'Edit', edit_direccion_path(@direccion) %> |
<%= link_to 'Back', direccions_path %>

app/views/index/inicio.html.erb
<h1>Index#inicio</h1>
<p>Find me in app/views/index/inicio.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Tarea7</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/usuarios/_form.html.erb
<%= form_for(@usuario) do |f| %>
  <% if @usuario.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@usuario.errors.count, "error") %> prohibited this usuario from being saved:</h2>

      <ul>
      <% @usuario.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nombre %><br>
    <%= f.text_field :nombre %>
  </div>
  <div class="field">
    <%= f.label :apellido %><br>
    <%= f.text_field :apellido %>
  </div>
  <div class="field">
    <%= f.label :fechanacimiento %><br>
    <%= f.date_select :fechanacimiento %>
  </div>
  <div class="field">
    <%= f.label :correo %><br>
    <%= f.text_field :correo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/usuarios/edit.html.erb
<h1>Editing Usuario</h1>

<%= render 'form' %>

<%= link_to 'Show', @usuario %> |
<%= link_to 'Back', usuarios_path %>

app/views/usuarios/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Usuarios</h1>

<table>
  <thead>
    <tr>
      <th>Nombre</th>
      <th>Apellido</th>
      <th>Fechanacimiento</th>
      <th>Correo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @usuarios.each do |usuario| %>
      <tr>
        <td><%= usuario.nombre %></td>
        <td><%= usuario.apellido %></td>
        <td><%= usuario.fechanacimiento %></td>
        <td><%= usuario.correo %></td>
        <td><%= link_to 'Show', usuario %></td>
        <td><%= link_to 'Edit', edit_usuario_path(usuario) %></td>
        <td><%= link_to 'Destroy', usuario, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Usuario', new_usuario_path %>

app/views/usuarios/new.html.erb
<h1>New Usuario</h1>

<%= render 'form' %>

<%= link_to 'Back', usuarios_path %>

app/views/usuarios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nombre:</strong>
  <%= @usuario.nombre %>
</p>

<p>
  <strong>Apellido:</strong>
  <%= @usuario.apellido %>
</p>

<p>
  <strong>Fechanacimiento:</strong>
  <%= @usuario.fechanacimiento %>
</p>

<p>
  <strong>Correo:</strong>
  <%= @usuario.correo %>
</p>

<%= link_to 'Edit', edit_usuario_path(@usuario) %> |
<%= link_to 'Back', usuarios_path %>